services:
  backend:
    build: .
    ports:
      - "3001:3000"
    command: sh -c "/wait && /out/server"
    environment:
      - DATABASE_URL=postgres://postgres@postgres:5432/postgres?sslmode=disable
      - STATIC_PATH=out/build
      - WAIT_HOSTS=postgres:5432
  postgres:
    image: "postgres:13-alpine"
    hostname: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - pg-data:/var/lib/postgresql/data
volumes:
  pg-data: